#!/bin/bash

logLocation="/var/log/photoframe"
installLog="$logLocation/install.log"
autoupLog="$logLocation/autoupdate.log"

mkdir -p $logLocation
touch $installLog $autoupLog
size=$(stat -c%s "$installLog")
if [ $size -gt 50 ]; then 
    rm -f $installLog
    touch $installLog
fi

export DEBIAN_FRONTEND=non-interactive

date=`date -uIns`; echo "${date::-11} Starting Install"

sudo apt-get --yes --autoremove --no-install-recommends install nodejs npm curl jq 2>&1

updateScript=`readlink -f "${BASH_SOURCE[0]}"`
updateScript=`dirname $updateScript`/UpdateFrame

cat << EOF > /etc/cron.d/photoframe
#Photoframe auto-updater code
# m h   dom mon dow user command
* *     * * *   root    $updateScript 2>&1 >> $autoupLog
EOF

sudo service cron reload
