#!/bin/bash


sudo apt install nodejs npm curl jq

updateScript=`dirname "$0"/UpdateFrame`

cat << EOF > /etc/cron.d/photoframe
#Photoframe auto-updater code

* * * * * $updateScript >/dev/null 2>&1
EOF
