#!/bin/bash

logLocation="/var/log/photoframe"
autoupLog="$logLocation/autoupdate.log"
installLog="$logLocation/install.log"

touch $autoupLog
size=`stat -c%s $autoupLog`
if [ $size -gt 50 ]; then
    rm -f $autoupLog
    touch $autoupLog 
fi

folder=`dirname "${BASH_SOURCE[0]}"`
cd $folder/../
last_install=`stat -c %Y scripts/InstallFrame`

gitcommitsurl="`git remote get-url origin | sed -re 's#(.*://(www.)?github.com)(.*)\.git#https://api.github.com/repos\3#'`/commits"
commitdate=`curl --silent $gitcommitsurl | jq '.[0].commit.committer.date'`
commitdate=`date "+%s" -d ${commitdate:1:-1}`
lastpull=`stat -c %Y .git/FETCH_HEAD`

if [ $commitdate -gt $lastpull ]; then
    echo "Updating git repo"
    git pull
    new_install=`stat -c %Y scripts/InstallFrame`
    if [ $last_install -lt $new_install ]; then
        echo "Install has updated, running InstallFrame"
        bash $folder/InstallFrame >> $installLog 2>>$autoupLog
    fi
else
    echo "No Change"
fi




#Add any service restarts here